import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { copy } from 'esbuild-plugin-copy';
import { sassPlugin } from 'esbuild-sass-plugin';

try { process.loadEnvFile(); } catch { /* no .env file */ }

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const dir = process.env.OUTDIR ? process.env.OUTDIR : "./build";

const map = {
    'src/main.ts': 'main',
    'src/scss/styles.scss': 'styles',
};

const entryPoints = Object.entries(map)
    .map(([k, v]) => {
        return { 'in': k, 'out': v };
    });

const parameters = {
    banner: {
        js: banner,
    },
    entryPoints,
    bundle: true,
    platform: 'node',
    external: [
        'obsidian',
        'electron',
        "codemirror",
        '@codemirror/language',
        '@codemirror/state',
        '@codemirror/view',
        'moment',
        ...builtinModules
    ],
    loader: {
        '.png': 'dataurl',
        '.woff': 'dataurl',
        '.woff2': 'dataurl',
        '.eot': 'dataurl',
        '.ttf': 'dataurl',
        '.svg': 'dataurl',
    },
    format: 'cjs',
    minify: prod,
    target: 'es2022',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outdir: dir,
    plugins: [
        sassPlugin({
            filter: /.(s[ac]ss|css)$/,
            loadPaths: [
                'node_modules/reveal.js/css',
            ],
        }),
        copy({
            assets: {
                from: ['manifest.json'],
                to: ['./manifest.json']
            }
        }),
        copy({
            assets: {
                from: ['README.md'],
                to: ['./README.md']
            }
        }),
        copy({
            assets: {
                from: ['distVersion.json'],
                to: ['./distVersion.json']
            }
        }),
        copy({
            assets: prod ? {} : {
                from: ['.hotreload'],
                to: ['.hotreload'],
            },
            once: true
        }),

    ],
};

if (prod) {
    await esbuild.build(parameters).catch((x) => {
        if (x.errors) {
            console.error(x.errors);
        } else {
            console.error(x);
        }
        process.exit(1)
    });
} else {
    const ctx = await esbuild.context(parameters);
    await ctx.watch();
}
